apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "talaria.servicename" . }}
  labels:
    app: {{ template "talaria.fullname" . }}
    env: {{ .Values.env }}
spec:
  serviceName: {{ template "talaria.servicename" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "talaria.servicename" . }}
      env: {{ .Values.cluster }}
  template:
    metadata:
      labels:
        app: {{ template "talaria.fullname" . }}
        env: {{ .Values.cluster }}
    spec:
      terminationGracePeriodSeconds: 30
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ template "stalker-processor.fullname" . }}
                topologyKey: kubernetes.io/hostname
        containers:
          - image: {{ .Values.talariaImage }}
            name: {{ template "talaria.servicename" . }}
            ports:
              - containerPort: 8042
                name: thrift
                protocol: TCP
              - containerPort: 7946
                protocol: TCP
              - containerPort: 7946
                protocol: UDP
            imagePullPolicy: IfNotPresent
            env:
              - name: TALARIA_CONF_URI
                value: {{ .Values.configPath }}
              - name: GOMAXPROCS
                value: "128"
              - name: AWS_ACCESS_KEY # Use https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables 
                value: ACCESSKEY
              - name: AWS_SECRET_KEY
                value: SECRETKEY
            securityContext:
              privileged: true 
            volumeMounts:
              - mountPath: /config
                name: 'config-dir'
              - mountPath: /data
                name: data
            resources:
              requests:
                memory: "1000Mi"
                cpu: "1000m"
        securityContext: {}
        volumes:
        - name: 'config-dir'
          hostPath:
            path: /hosthome/crphang/charts/talaria/config
        volumeClaimTemplates:
          - metadata:
            name: data
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: standard
              resources:
                requests:
                  storage: 1000Gi
              
               
              
