apiVersion: v1
kind: Service
metadata:
  name: "{{ template "talaria.servicename" . }}-headless-svc"
spec:
  clusterIP: None
  selector:
    app: {{ template "talaria.fullname" . }}
  ports:
  - protocol: TCP
    port: 8042
    targetPort: 8042