apiVersion: v1
kind: Service
metadata:
  name: {{ template "talaria.fullname" . }}-loadbalancer-thrift
spec:
  type: LoadBalancer
  selector:
    app: {{ template "talaria.fullname" . }}
  ports:
    - port: 8042
      targetPort: 8042
      name: thrift