apiVersion: v1
kind: Service
metadata:
  name: {{ template "talaria.fullname" . }}-loadbalancer-grpc
spec:
  type: LoadBalancer
  selector:
    app: {{ template "talaria.fullname" . }}
  ports:
    - port: 8080
      targetPort: 8080
      name: grpc